import { useState } from 'react'
import {
  ChefHat, Flame, Dumbbell, Bookmark, BookmarkCheck,
  Wheat, Droplets, AlertTriangle, CheckSquare, Square,
  Copy, Check, RefreshCw, CalendarPlus,
} from 'lucide-react'
import { setSlot, DAYS, SLOTS } from '../lib/planner'

function MacroChip({ icon: Icon, value, label }) {
  if (!value) return null
  return (
    <div className="flex items-center gap-1 sm:gap-1.5 rounded-lg px-2 sm:px-3 py-1 sm:py-1.5 text-xs sm:text-sm font-semibold bg-white/20">
      <Icon className="w-3 h-3 sm:w-3.5 sm:h-3.5 flex-shrink-0" />
      <span>{value}</span>
      {label && <span className="opacity-75 text-[10px] sm:text-xs font-normal">{label}</span>}
    </div>
  )
}

function macrosAreSuspect(meal) {
  const p = parseFloat(String(meal.protein  || '0').replace(/[^0-9.]/g, ''))
  const c = parseFloat(String(meal.calories || '0').replace(/[^0-9.]/g, ''))
  if (!p || !c) return false
  return c < p * 4 * 0.8
}

function formatRecipeAsText(meal) {
  return [
    `🍽️ ${meal.name}`,
    `📊 ${meal.protein} protein | ${meal.calories} cal | ${meal.carbs} carbs | ${meal.fat} fat`,
    '',
    '🧂 INGREDIENTS',
    ...(meal.ingredients || []).map(i => `  • ${i}`),
    '',
    '📋 INSTRUCTIONS',
    ...(meal.steps || []).map((s, i) => `  ${i + 1}. ${s}`),
    '',
    '— Generated by ProteinFuel AI',
  ].join('\n')
}

// Mini planner popover
function AddToPlannerPopover({ meal, onClose }) {
  const [day,   setDay]   = useState(DAYS[0])
  const [slot,  setSlot_] = useState(SLOTS[0])
  const [added, setAdded] = useState(false)

  function confirm() {
    setSlot(day, slot_, { name: meal.name, protein: meal.protein, calories: meal.calories, carbs: meal.carbs, fat: meal.fat, type: 'home_cooked' })
    setAdded(true)
    setTimeout(onClose, 1200)
  }

  return (
    <div className="absolute top-full right-0 mt-2 z-30 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl shadow-xl p-4 w-64 animate-slide-down" onClick={e => e.stopPropagation()}>
      {added ? (
        <p className="text-center text-emerald-500 font-semibold text-sm py-2">✅ Added to {day} {slot_}!</p>
      ) : (
        <>
          <p className="font-bold text-slate-900 dark:text-white text-xs mb-3">Add to Weekly Planner</p>
          <div className="space-y-2 mb-3">
            <div>
              <label className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-1">Day</label>
              <select value={day} onChange={e => setDay(e.target.value)}
                className="w-full px-3 py-2 rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-white text-xs font-semibold focus:outline-none">
                {DAYS.map(d => <option key={d} value={d}>{d}</option>)}
              </select>
            </div>
            <div>
              <label className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block mb-1">Meal Slot</label>
              <select value={slot_} onChange={e => setSlot_(e.target.value)}
                className="w-full px-3 py-2 rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-white text-xs font-semibold focus:outline-none">
                {SLOTS.map(s => <option key={s} value={s}>{s}</option>)}
              </select>
            </div>
          </div>
          <div className="flex gap-2">
            <button onClick={confirm} className="flex-1 py-2 rounded-xl bg-indigo-500 text-white text-xs font-bold hover:bg-indigo-600 transition-colors">Add</button>
            <button onClick={onClose} className="px-3 py-2 rounded-xl border border-slate-200 dark:border-slate-700 text-xs font-semibold text-slate-600 dark:text-slate-400">Cancel</button>
          </div>
        </>
      )}
    </div>
  )
}

export default function HomeCookedCard({ meal, onSave, saved, onRegenerate, regenLoading }) {
  const [checkedIngredients, setCheckedIngredients] = useState(new Set())
  const [checkedSteps,       setCheckedSteps]       = useState(new Set())
  const [copied,             setCopied]              = useState(false)
  const [showPlanner,        setShowPlanner]         = useState(false)
  const suspect = macrosAreSuspect(meal)

  function toggleIngredient(i) {
    setCheckedIngredients(prev => { const n = new Set(prev); n.has(i) ? n.delete(i) : n.add(i); return n })
  }
  function toggleStep(i) {
    setCheckedSteps(prev => { const n = new Set(prev); n.has(i) ? n.delete(i) : n.add(i); return n })
  }

  async function copyRecipe() {
    await navigator.clipboard.writeText(formatRecipeAsText(meal))
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const allStepsDone = meal.steps?.length > 0 && checkedSteps.size === meal.steps.length

  return (
    <div className="bg-white/90 dark:bg-slate-900/90 backdrop-blur-sm rounded-xl sm:rounded-2xl border border-slate-200/80 dark:border-slate-700/50 overflow-hidden shadow-sm animate-slide-up">

      {/* Header band */}
      <div className="bg-gradient-to-br from-emerald-500 via-emerald-500 to-teal-500 p-4 sm:p-6 text-white">
        <div className="flex items-start justify-between gap-3 sm:gap-4">
          <div className="min-w-0 flex-1">
            <div className="flex items-center gap-1.5 sm:gap-2 mb-1.5 sm:mb-2 opacity-90">
              <div className="w-5 h-5 sm:w-6 sm:h-6 rounded-md sm:rounded-lg bg-white/20 flex items-center justify-center flex-shrink-0">
                <ChefHat className="w-3 h-3 sm:w-3.5 sm:h-3.5" />
              </div>
              <span className="text-xs sm:text-sm font-semibold tracking-wide">Home Cooked</span>
            </div>
            <h2 className="text-lg sm:text-xl lg:text-2xl font-extrabold leading-tight">{meal.name}</h2>
            <p className="mt-1 sm:mt-1.5 text-xs sm:text-sm opacity-85 leading-relaxed">{meal.description}</p>
          </div>

          {/* Action buttons */}
          <div className="flex flex-col items-end gap-2 flex-shrink-0">
            {onSave && (
              <button onClick={onSave} disabled={saved}
                className="w-9 h-9 sm:w-10 sm:h-10 rounded-xl bg-white/20 hover:bg-white/30 disabled:opacity-60 transition-colors flex items-center justify-center"
                title={saved ? 'Saved!' : 'Save recipe'}>
                {saved ? <BookmarkCheck className="w-4 h-4 sm:w-5 sm:h-5" /> : <Bookmark className="w-4 h-4 sm:w-5 sm:h-5" />}
              </button>
            )}
            <button onClick={copyRecipe}
              className="w-9 h-9 sm:w-10 sm:h-10 rounded-xl bg-white/20 hover:bg-white/30 transition-colors flex items-center justify-center"
              title="Copy recipe">
              {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
            </button>
            {onRegenerate && (
              <button onClick={onRegenerate} disabled={regenLoading}
                className="w-9 h-9 sm:w-10 sm:h-10 rounded-xl bg-white/20 hover:bg-white/30 disabled:opacity-60 transition-colors flex items-center justify-center"
                title="Regenerate this meal">
                <RefreshCw className={`w-4 h-4 ${regenLoading ? 'animate-spin' : ''}`} />
              </button>
            )}
            {/* Add to planner */}
            <div className="relative">
              <button
                onClick={() => setShowPlanner(v => !v)}
                className="w-9 h-9 sm:w-10 sm:h-10 rounded-xl bg-white/20 hover:bg-white/30 transition-colors flex items-center justify-center"
                title="Add to weekly planner">
                <CalendarPlus className="w-4 h-4" />
              </button>
              {showPlanner && (
                <AddToPlannerPopover meal={meal} onClose={() => setShowPlanner(false)} />
              )}
            </div>
          </div>
        </div>

        {/* Macro chips */}
        <div className="mt-3 sm:mt-4 flex flex-wrap gap-1.5 sm:gap-2">
          <MacroChip icon={Dumbbell} value={meal.protein}  label="protein" />
          <MacroChip icon={Flame}    value={meal.calories} label="cal" />
          <MacroChip icon={Wheat}    value={meal.carbs}    label="carbs" />
          <MacroChip icon={Droplets} value={meal.fat}      label="fat" />
        </div>

        {suspect && (
          <div className="mt-3 flex items-center gap-1.5 bg-amber-500/20 rounded-lg px-3 py-1.5 text-xs font-medium text-amber-100">
            <AlertTriangle className="w-3.5 h-3.5 flex-shrink-0" />
            Macros may be inaccurate — try regenerating this meal
          </div>
        )}
        {allStepsDone && (
          <div className="mt-3 flex items-center gap-1.5 bg-white/20 rounded-lg px-3 py-1.5 text-xs font-semibold">
            ✅ All steps complete — enjoy your meal!
          </div>
        )}
      </div>

      {/* Body */}
      <div className="p-4 sm:p-6 grid grid-cols-1 md:grid-cols-2 gap-5 sm:gap-8">

        {/* Ingredients — tap to check off */}
        {meal.ingredients?.length > 0 && (
          <div>
            <div className="flex items-center justify-between mb-3 sm:mb-4">
              <h3 className="text-[10px] sm:text-[11px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest">Ingredients</h3>
              {checkedIngredients.size === meal.ingredients.length && (
                <span className="text-[10px] text-emerald-500 font-semibold">All gathered!</span>
              )}
            </div>
            <ul className="space-y-2 sm:space-y-2.5">
              {meal.ingredients.map((ing, i) => {
                const done = checkedIngredients.has(i)
                return (
                  <li key={i} onClick={() => toggleIngredient(i)}
                    className={`flex items-start gap-2 sm:gap-2.5 text-xs sm:text-sm cursor-pointer select-none transition-colors ${done ? 'text-slate-400 dark:text-slate-600 line-through' : 'text-slate-700 dark:text-slate-300'}`}>
                    {done
                      ? <CheckSquare className="w-4 h-4 text-emerald-500 flex-shrink-0 mt-0.5" />
                      : <Square      className="w-4 h-4 text-slate-300 dark:text-slate-600 flex-shrink-0 mt-0.5" />
                    }
                    {ing}
                  </li>
                )
              })}
            </ul>
          </div>
        )}

        {/* Steps — tap to check off */}
        {meal.steps?.length > 0 && (
          <div>
            <h3 className="text-[10px] sm:text-[11px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest mb-3 sm:mb-4">Instructions</h3>
            <ol className="space-y-3 sm:space-y-4">
              {meal.steps.map((step, i) => {
                const done = checkedSteps.has(i)
                return (
                  <li key={i} onClick={() => toggleStep(i)} className="flex gap-2.5 sm:gap-3 cursor-pointer select-none group">
                    <span className={`flex-shrink-0 w-5 h-5 sm:w-6 sm:h-6 rounded-full text-[10px] sm:text-xs font-bold flex items-center justify-center mt-0.5 transition-colors ${
                      done ? 'bg-emerald-500 text-white' : 'bg-emerald-100 dark:bg-emerald-900/40 text-emerald-700 dark:text-emerald-400 group-hover:bg-emerald-200 dark:group-hover:bg-emerald-900/60'
                    }`}>
                      {done ? '✓' : i + 1}
                    </span>
                    <p className={`text-xs sm:text-sm leading-relaxed transition-colors mt-0.5 ${done ? 'text-slate-400 dark:text-slate-600 line-through' : 'text-slate-700 dark:text-slate-300'}`}>
                      {step}
                    </p>
                  </li>
                )
              })}
            </ol>
          </div>
        )}
      </div>
    </div>
  )
}
